# Generated by Django 5.0.6 on 2024-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет'),
        ),
    ]
